### PR TITLE
Text updates - some threshold elements

### PR DESCRIPTION
**Pull request by derekpierre**
Here's what I could get done before my kids woke up.

- Add text blurbs to home page, and wrapping page.
- Add threshold branding image.
- Modify text shown in wrap dialog - T value in purple (branding), common decimal places for NU / KEEP values and T value.

Side note: value shown in wrap KEEP dialog shows available tokens in "NU" not "KEEP" - couldn't figure out why that was in time. See screenshot below.
Screen Shot 2022-01-01 at 9 17 34 AM

### CODE REVIEW

**Comment by KPrasch** [comment]
Hey @derekpierre! Thanks for making this PR on New Year's Day 🛩️  I may have overlapped your work a bit here in PR #147 .  Also, here's a revival of the FAQ accordion that might benefit from attention.  

https://github.com/nucypher/nuit/blob/b0d99b72178ee67416b9c8375e85e1662cc8af42/packages/react-app/src/pages/manage/new/wrapping_faq.json

> Side note: value shown in wrap KEEP dialog shows available tokens in "NU" not "KEEP" - couldn't figure out why that was in time. See screenshot below.

This is fixed in my PR - there was a missing content variable.

**Comment by vepkenez** [comment]
> Side note: value shown in wrap KEEP dialog shows available tokens in "NU" not "KEEP" - couldn't figure out why that was in time. See screenshot below.

I think if you add a label=“T”param to that it will use that instead 
-edit: no not on this element actually

**Comment by vepkenez** [comment]
Loving that purple!

**Comment by derekpierre** [comment]
@KPrasch I'll try to rework over your PR.

**Comment by derekpierre** [comment]
Replaced by #148 .

**Pull request closed without merging**
